import { Member, Expense, AttendanceSession, Settlement, AuditLog } from '../types';

export const initialMembers: Member[] = [
  {
    id: 'm_1',
    name: 'Sharath Chandra',
    email: 'sharathhc529@gmail.com',
    phone: '+91 98765 43210',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Sharath',
    isActive: true,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'm_2',
    name: 'Arun Kumar',
    email: 'arun.k@example.com',
    phone: '+91 98450 11223',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Arun',
    isActive: true,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'm_3',
    name: 'Karthik Rao',
    email: 'karthik.r@example.com',
    phone: '+91 97410 44556',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Karthik',
    isActive: true,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'm_4',
    name: 'Manoj Gowda',
    email: 'manoj.g@example.com',
    phone: '+91 99001 77889',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Manoj',
    isActive: true,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'm_5',
    name: 'Priya Sharma',
    email: 'priya.s@example.com',
    phone: '+91 98112 33445',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Priya',
    isActive: true,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
];

// Seed attendance for current month (September 2026) demonstrating differing attendance counts
// e.g., Sharath attended 5 days, Arun attended 4 days, Karthik attended 3 days, Manoj attended 2 days, Priya attended 1 day
export const initialAttendanceSessions: AttendanceSession[] = [
  {
    id: 'att_2026-09-01',
    date: '2026-09-01',
    timeSlot: '06:00 AM - 07:00 AM',
    attendeeIds: ['m_1', 'm_2', 'm_3', 'm_4'],
    notes: 'Morning warm-up doubles match',
    updatedBy: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    updatedAt: '2026-09-01T07:15:00.000Z',
  },
  {
    id: 'att_2026-09-02',
    date: '2026-09-02',
    timeSlot: '06:00 AM - 07:00 AM',
    attendeeIds: ['m_1', 'm_2', 'm_3'],
    notes: 'Court 2 booked for 1 hour',
    updatedBy: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    updatedAt: '2026-09-02T07:10:00.000Z',
  },
  {
    id: 'att_2026-09-03',
    date: '2026-09-03',
    timeSlot: '06:00 AM - 07:00 AM',
    attendeeIds: ['m_1', 'm_2', 'm_4'],
    guestAttendees: [{ name: 'Vikas (Guest)', phone: '+91 99999 11111', feeCharged: 150 }],
    notes: 'Guest Vikas joined for game',
    updatedBy: { uid: 'user_2', name: 'Arun Kumar', email: 'arun.k@example.com' },
    updatedAt: '2026-09-03T07:20:00.000Z',
  },
  {
    id: 'att_2026-09-04',
    date: '2026-09-04',
    timeSlot: '06:00 AM - 07:00 AM',
    attendeeIds: ['m_1', 'm_3', 'm_5'],
    notes: 'Friday friendly tournament',
    updatedBy: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    updatedAt: '2026-09-04T07:12:00.000Z',
  },
  {
    id: 'att_2026-09-07',
    date: '2026-09-07',
    timeSlot: '06:00 AM - 07:00 AM',
    attendeeIds: ['m_1', 'm_2'],
    notes: 'Singles drill session',
    updatedBy: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    updatedAt: '2026-09-07T07:05:00.000Z',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp_1',
    title: 'Monthly Court Booking (September)',
    amount: 5000,
    date: '2026-09-01',
    category: 'court_monthly',
    paidById: 'm_1',
    paidByName: 'Sharath Chandra',
    splitType: 'monthly_attendance_weighted',
    monthTarget: '2026-09',
    splits: [
      { memberId: 'm_1', memberName: 'Sharath Chandra', amount: 1667, daysAttended: 5 },
      { memberId: 'm_2', memberName: 'Arun Kumar', amount: 1333, daysAttended: 4 },
      { memberId: 'm_3', memberName: 'Karthik Rao', amount: 1000, daysAttended: 3 },
      { memberId: 'm_4', memberName: 'Manoj Gowda', amount: 667, daysAttended: 2 },
      { memberId: 'm_5', memberName: 'Priya Sharma', amount: 333, daysAttended: 1 },
    ],
    notes: 'September month morning 6-7 AM court slot booked at Smash Arena',
    createdBy: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    createdAt: '2026-09-01T08:30:00.000Z',
  },
  {
    id: 'exp_2',
    title: 'Yonex Mavis 350 Shuttles (Pack of 6)',
    amount: 950,
    date: '2026-09-03',
    category: 'shuttles',
    paidById: 'm_2',
    paidByName: 'Arun Kumar',
    splitType: 'all',
    splits: [
      { memberId: 'm_1', memberName: 'Sharath Chandra', amount: 190 },
      { memberId: 'm_2', memberName: 'Arun Kumar', amount: 190 },
      { memberId: 'm_3', memberName: 'Karthik Rao', amount: 190 },
      { memberId: 'm_4', memberName: 'Manoj Gowda', amount: 190 },
      { memberId: 'm_5', memberName: 'Priya Sharma', amount: 190 },
    ],
    notes: 'Green cap nylon shuttles',
    createdBy: { uid: 'user_2', name: 'Arun Kumar', email: 'arun.k@example.com' },
    createdAt: '2026-09-03T09:00:00.000Z',
  },
  {
    id: 'exp_3',
    title: 'Energy Drinks & Electrolytes',
    amount: 360,
    date: '2026-09-04',
    category: 'snacks',
    paidById: 'm_3',
    paidByName: 'Karthik Rao',
    splitType: 'specific',
    splits: [
      { memberId: 'm_1', memberName: 'Sharath Chandra', amount: 120 },
      { memberId: 'm_3', memberName: 'Karthik Rao', amount: 120 },
      { memberId: 'm_5', memberName: 'Priya Sharma', amount: 120 },
    ],
    notes: 'Only for Friday game attendees',
    createdBy: { uid: 'user_3', name: 'Karthik Rao', email: 'karthik.r@example.com' },
    createdAt: '2026-09-04T08:45:00.000Z',
  },
];

export const initialSettlements: Settlement[] = [
  {
    id: 'set_1',
    date: '2026-09-05',
    fromMemberId: 'm_2',
    fromMemberName: 'Arun Kumar',
    toMemberId: 'm_1',
    toMemberName: 'Sharath Chandra',
    amount: 1000,
    paymentMethod: 'UPI',
    notes: 'GPay transfer for monthly court share',
    recordedBy: { uid: 'user_2', name: 'Arun Kumar', email: 'arun.k@example.com' },
    createdAt: '2026-09-05T10:00:00.000Z',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    timestamp: '2026-09-01T08:30:00.000Z',
    user: { uid: 'user_1', name: 'Sharath Chandra', email: 'sharathhc529@gmail.com' },
    action: 'CREATE_EXPENSE',
    targetType: 'expense',
    description: 'Sharath added expense "Monthly Court Booking (September)" of ₹5,000 with attendance-weighted split',
  },
  {
    id: 'log_2',
    timestamp: '2026-09-03T09:00:00.000Z',
    user: { uid: 'user_2', name: 'Arun Kumar', email: 'arun.k@example.com' },
    action: 'CREATE_EXPENSE',
    targetType: 'expense',
    description: 'Arun added expense "Yonex Mavis 350 Shuttles" of ₹950 split equally among all members',
  },
  {
    id: 'log_3',
    timestamp: '2026-09-05T10:00:00.000Z',
    user: { uid: 'user_2', name: 'Arun Kumar', email: 'arun.k@example.com' },
    action: 'RECORD_SETTLEMENT',
    targetType: 'settlement',
    description: 'Arun recorded a UPI payment settlement of ₹1,000 to Sharath',
  },
];
